### ISSUE TITLE
Performance Improvement: getReviewResponses

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/conforma-server#1078]
# Summary

The `getReviewResponses` seems to be called frequently within the application, and has sometimes shown very slow performance on production servers. e.g. taking 30seconds!

![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/37b98f08-0d9f-41aa-a3d3-38f90db92336)

![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/1346340e-92ee-40e9-af46-4be03c361cb3)

During completing a review this was called 6 times resulting in around 3minutes of waiting time for the user.
![image](https://github.com/msupply-foundation/conforma-server/assets/8287373/ccbb0585-b7fe-47b8-8cec-1ea17a947748)

# Why is it slow?

It's not clear! Seems to be fast locally, and reasonably fast on some servers.

# How concerned are we?

This is the biggest slow down for users who need to approve applications. 
It appears that moving to different server infrastructure might have helped, so maybe was a hardware issue?

# Possible Solutions:

Needs more investigation.

# Agreed Solution
TBD

**Comment by CarlosNZ** [comment]
Sorted (for now) with latest changes
