### ISSUE TITLE
Postgres 12.18 upgrade problem

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-server#1090]
There is a compatibility problem with newly released Postgres 12.18 and our database snapshots. When trying to load one, they fail with numerous errors. Ideally we'd just stay on Postgres 12.17 until we can sort out what's going on. The problem is, we can't make a new Docker build as it will always attempt to install PG12.18 when creating the image. 12.17 has basically been removed from all online repositories (apt, brew etc), presumably because of potential security vulnerabilities. Plus, it's pretty hard to install locally once you've upgraded (I have a workaround for now, but it's a bit of a hassle).

Ultimately, we need to figure out why our database restore is not compatible and fix it. But in the meantime, I think the best thing to do would be to use an existing docker image (e.g. https://hub.docker.com/layers/library/postgres/12.17/images/sha256-0464e78684f36c6901d71389297ec356cbf495f6cfb240aff25ee85da6398ea0) and compose it with ours, though I'm not 100% clear how to do that and how much re-configuring our process would be required.

But it is urgent, because we can't make any new builds for Fiji or Angola until this is sorted.

**Comment by craigdrown** [comment]
Any reason we can't skip to v14/15/16?

**Comment by CarlosNZ** [comment]
> Any reason we can't skip to v14/15/16?

I briefly tried 15 and it had the same problem when importing (pg_restore). It's possible we just need to use the correct version of pg_dump/pg_restore for each version, but I'm not even sure if that's something that is required, so need to look into it a bit more.

I agree though, moving up to a higher postgres version as part of fixing this seems like a sensible thing to do.

**Comment by CarlosNZ** [comment]
@EthanMcQ-TMF -- not sure if you have any insights into how to sort this, but maybe you could have a bit of a poke into it if you have time? It might be a bit of a can of worms, so just have a chat to me with anything you figure out.

Ideally we'd figure out what the problem with our database is that it doesn't like, and fix that, but a workaround to get Docker building would do for now.

**Comment by andreievg** [comment]
Food for thought, should be able to build from a specific layer in previous image (if you built it locally)
https://stackoverflow.com/questions/54413239/build-docker-image-from-specific-layer-of-image

I think if you pulled an image you can't quite get to the sha of the line, in which case we can just with our image and just start at this step: https://github.com/msupply-foundation/conforma-server/blob/465177dd3842c27fbb2fb517d3263f1039efb288/docker/Dockerfile#L60

**Comment by CarlosNZ** [comment]
I thought I'd managed to restore this using later Postgres versions, but unfortunately that's not the case. It appears that whatever has changed has affected *all* minor updates [released on Feb 8th](https://www.postgresql.org/about/news/postgresql-162-156-1411-1314-and-1218-released-2807/). In other words, I can restore using v 12.17, 14.10, 15.5, etc, but as soon as I try with the latest minors (12.18, 14.11, 15.6, etc), we have the same problem.

I have filed a bug report through the official [bug reporting form](https://www.postgresql.org/account/submitbug/), but no idea if/when we could expect any insight/fix from that.

Would be good to have a bit of a brainstorm to try and make a plan to handle this, as there won't be any more bug fixes for Angola or Fiji until we figure out a solution 😔.

**Comment by CarlosNZ** [comment]
Just posting the error log here as a reference:

```
Command failed: pg_restore -U postgres --clean --if-exists --dbname tmf_app_manager /Users/carl/GitHub/conforma/conforma-server/database/_snapshots/TEST_14_11_2024-03-14_15-27-40/database.dump
pg_restore: error: could not execute query: ERROR: relation "public.template" does not exist
LINE 5: public.template
^
QUERY:
SELECT
template.code
FROM
public.template
JOIN public.template_section ON template_id = template.id
WHERE
template_section.id = $1;


CONTEXT: SQL function "get_template_code" during inlining
Command was: CREATE TABLE public.template_element (
id integer NOT NULL,
section_id integer NOT NULL,
code character varying NOT NULL,
index integer,
title character varying,
category public.template_element_category,
element_type_plugin_code character varying,
visibility_condition jsonb DEFAULT 'true'::jsonb,
is_required jsonb DEFAULT 'true'::jsonb,
is_editable jsonb DEFAULT 'true'::jsonb,
validation jsonb DEFAULT 'true'::jsonb,
initial_value jsonb,
validation_message character varying,
help_text character varying,
parameters jsonb,
reviewability public.reviewability DEFAULT 'ONLY_IF_APPLICANT_ANSWER'::public.reviewability NOT NULL,
template_code character varying GENERATED ALWAYS AS (public.get_template_code(section_id)) STORED,
template_version character varying GENERATED ALWAYS AS (public.get_template_version(section_id)) STORED
);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE public.template_element OWNER TO postgres;

pg_restore: error: could not execute query: ERROR: type public.template_element does not exist
Command was: CREATE FUNCTION public.template_element_parameters_string(template_element public.template_element) RETURNS text
LANGUAGE sql STABLE
AS $_$
SELECT
parameters::text
FROM
public.template_element
WHERE
id = $1.id
$_$;


pg_restore: error: could not execute query: ERROR: type "public.template_element" does not exist
Command was: ALTER FUNCTION public.template_element_parameters_string(template_element public.template_element) OWNER TO postgres;

pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER SEQUENCE public.template_element_id_seq OWNED BY public.template_element.id;


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.template_element ALTER COLUMN id SET DEFAULT nextval('public.template_element_id_seq'::regclass);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: COPY public.template_element (id, section_id, code, index, title, category, element_type_plugin_code, visibility_condition, is_required, is_editable, validation, initial_value, validation_message, help_text, parameters, reviewability) FROM stdin;
pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.template_element
ADD CONSTRAINT template_element_pkey PRIMARY KEY (id);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.template_element
ADD CONSTRAINT template_element_template_code_code_template_version_key UNIQUE (template_code, code, template_version);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: CREATE INDEX i_template_element_category ON public.template_element USING btree (category);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: CREATE INDEX i_template_element_code ON public.template_element USING btree (code);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: CREATE INDEX i_template_element_reviewability ON public.template_element USING btree (reviewability);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: CREATE INDEX i_template_element_section_id_fkey ON public.template_element USING btree (section_id);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: CREATE INDEX i_template_element_template_code ON public.template_element USING btree (template_code);


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.application_response
ADD CONSTRAINT application_response_template_element_id_fkey FOREIGN KEY (template_element_id) REFERENCES public.template_element(id) ON DELETE CASCADE;


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.review_response
ADD CONSTRAINT review_response_template_element_id_fkey FOREIGN KEY (template_element_id) REFERENCES public.template_element(id) ON DELETE CASCADE;


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: ALTER TABLE ONLY public.template_element
ADD CONSTRAINT template_element_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.template_section(id) ON DELETE CASCADE;


pg_restore: error: could not execute query: ERROR: relation "public.template_element" does not exist
Command was: GRANT ALL ON TABLE public.template_element TO graphile_user;


pg_restore: warning: errors ignored on restore: 18
```

**Comment by CarlosNZ** [comment]
UPDATE: I have a workaround for this now -- just need to build using a "multi-stage" Docker build using one of the older images as the base. That'll do in the meantime so at least we can keep doing fixes.

As for the actual problem -- I've received a reply from my bug report that offers some insights to hopefully move forward. Looks like their may be a problem with one (or more) of our function definitions. I'll need to spend a bit of time looking at this properly and making sure we can fix it as well as nicely migrate our existing snapshots, so I won't do that now but I'll look at it sometime in the near future.

**Comment by CarlosNZ** [comment]
The info I've got from the Postgres community is that the error is likely caused by using a non-IMMUTABLE function for a generated column. We've declared it IMMUTABLE, but it actually isn't, which is likely to cause problems somewhere, sometime.

As for why it broke *now*:

> BTW, I believe that what broke it for you as of the current releases
is commits 743ddafc7 et al, which caused GENERATED expressions to be
run through expression preprocessing at CREATE TABLE time:

   > Two actual bugs of this ilk are fixed here.  We failed to preprocess
   column GENERATED expressions before checking mutability, so that the
   code could fail to detect the use of a volatile function
   default-argument expression, or it could reject a polymorphic function
   that is actually immutable on the datatype of interest.  Likewise,
   column DEFAULT expressions weren't preprocessed before determining if
   it's safe to apply the attmissingval mechanism.  A false negative
   would just result in an unnecessary table rewrite, but a false
   positive could allow the attmissingval mechanism to be used in a case
   where it should not be, resulting in unexpected initial values in a
   new column.

And the "correct" way to do what we're doing is:

> You should instead use a trigger to populate template_code.  That is the correct solution,
and then you wouldn't get that error.

So we need to find all the places where we've used a non-IMMUTABLE function in a generated column and replace them with triggers (or we could use VIEWS, but that might require too much updating in our front-end queries).

Here is the list of ALL generated columns, and what needs to be changed to keep existing functionality:

- The columns `template_code` and `template_version` in the `template_element` table:
  - delete get_template_code and get_template_version functions
  - change columns to VARCHAR, not GENERATED
  - add trigger to `template_element` to update these columns on creation
  - add trigger to `template` to refresh these columns whenever template is created or modified
- `application_id` column on `application_status_history` table:
  - this shouldn't change, so we only need a trigger for when a record is created on this table
- several columns on `review` table: `application_id`, `reviewer_id`, `level_number`, `stage_number`, `time_stage_created`, `is_last_level`, `is_last_stage`:
  - I think (but this needs to be confirmed) that all these fields wouldn't change after creation, so a single trigger to fill the values on record insert should be all that is required
- `template_id` column on `review_assignment`:
  - again, this should only need to be calculated once on record insert
- `stage_number` on review_response:
  - trigger to calculate once on insert
- `full_name` on `user` table:
  - this one is actually a legit use of a generated column (uses only data from current table/row), so no change required here.

Changing the column types will have to be done as migration (drop and recreate), but the triggers/functions themselves should be defined in the overall `views_functions_triggers` SQL script that runs every migration and snapshot load.

We also need to be vigilant about deleting prior versions of these functions to avoid clutter (delete them in `views_functions_triggers`)

My estimate is that this is about 1 day's work, but would allow a bit more for decent testing and troubleshooting.

**Comment by CarlosNZ** [comment]
> My estimate is that this is about 1 day's work, but would allow a bit more for decent testing and troubleshooting.

Before we go ahead, though, I would suggest just deleting all those functions and columns completely and seeing if the snapshot can be dumped/restored using the newest Postgres versions so we're certain that this will actually fix the problem at hand.

**Comment by CarlosNZ** [comment]
Let's make v0.8 the version with these changes in it and build it with Postgres 12.17 (as now). This will be the last build that can handle the "bad" database files and will need to be kept so we can use it whenever we need to migrate an older snapshot to the "fixed" format.

Then make a new build called 0.9 that builds with the new Postgres version. This version will refuse to load a snapshot saved with anything lower than 0.8.
