### ISSUE TITLE
UAT Bug: Password reset & internal user creation

### ISSUE THREAD

**Issue by jagoje** [msupply-foundation/conforma-server#1091]
The issue with resetting passwords is affecting two workflows:
1. Creating internal users
2. Forgetting passwords

**Create internal user**

At the last step of the create internal user process when you have to set the password we are receiving the following error message upon pressing submit:

Link: https://conforma-demo.msupply.org:50008/application/S-LFQ-0278/submission

![Image](https://github.com/msupply-foundation/conforma-web-app/assets/88009219/3c5c48df-f89f-4679-a80b-47b06ea85071)

**Forgot password**
Same error occurs for forgot password

**Comment by jagoje** [comment]
@regotaina - could you please check if this is still occuring?

**Comment by regotaina** [comment]
> @regotaina - could you please check if this is still occuring?

It's working now :)
