### ISSUE TITLE
Memoise application list actions to speed up performance

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-server#1103]
There are four columns returned by the application_list function that are causing significant performance burdens:

- assigners (list of users who can assign current stage)
- reviewers (list of reviewers who *are* assigned to current stage)
- reviewer_action (what the current user/reviewer can do next to an application)
- assigner_action (what the current user/assigner can do next to an application)

The last two in particular make large demands, as they return different values depending on the user. Plus they are calculated (using fairly convoluted functions) for every application (of a particular type) on every request, even ones that don't appear in the results (as they must be filterable on those fields)

It makes sense to memoise these values and store them in the database, so we only need to calculate them once, and update them whenever an event occurs that would change them (for a specific user).

I suggest storing this info as follows:

- In existing `application` table, add two new columns for the lists:
  - `reviewer_list` (array of strings)
  - `assigner_list` (array of strings)
- New table: `application_reviewer_action` with the following columns:
  - `user_id`
  - `application_id`
  - `reviewer_action`
  - `assigner_action`
(Probably add a UNIQUE constraint on the four fields (as a combo) as well)

Then it's just the matter of capturing the events to trigger updates. I think we just need to trigger on
- create/update/delete of `review_assignments`
- create of `review_status_history` records

The trigger would then call a function that does the following:
- get the `reviewer_id`, `assigner_id` and the `application_id` related to the record in question (for `review_assignment` these are all directly on the table, for `review_status_history` and extra sub-query would be required)
- calculate the "reviewer_action" and "assigner_action" for each (using existing PG functions)
- delete all `application_reviewer_action` for this users/application combo (assigner and reviewer)
- re-insert records with new info
- fetch reviewer_list and assigner_list for this application_id (using existing PG functions)
- update the `reviewer_list` and `assigner_list` fields of the application

We don't need to worry about permissions -- we'll only be doing this for a particular user/application combo at one time, and will only be triggered by interacting with an application, which they must have already had permission to do.  

From there, we can ditch the current `application_list` function and just create a view that joins `application` to `application_reviewer_action`, and the list query would just be a simple query of this view (we might not even need a view, it could be fine to just connect them using graphQL query shape)

I think all the complicated logic to _determine_ these actions is already done and working fine -- so this refactor would only reduce the number of times we need to call these functions, but not change the underlying logic.

I also think that after this, we can fetch the total count as part of the same single query to the list, but we'll see.

**Comment by andreievg** [comment]
Thanks @CarlosNZ, I like this, overall. Some preliminary comments:

* How would this trigger be activated ? (database trigger/queue ?)
* For the new application list view, can a user access actions for other users (and would it even be a problem if they do ?)

**Comment by CarlosNZ** [comment]
> * How would this trigger be activated ? (database trigger/queue ?)

Database trigger and function (so all internal to Postgres)

> * For the new application list view, can a user access actions for other users (and would it even be a problem if they do ?)

Row level permissions should still restrict the applications returned. And yes, I guess in principle you could pass someone else's user id as a parameter, but:
1. You can already do that now (userId is just a graphQL parameter, there's no security associated with it)
2. I don't think it really matters. The only way it could be abused is if a particularly astute applicant wants to see who's been assigned they could look for a reviewer actions associated with their application. But they'd only get reviewer IDs and they can't really match them to people. But yes, in theory it's not perfect. But there are a number of weaknesses like this already due to the fairly open GraphQL layer, something which would be remedied overall by having more restricted endpoints.

**Comment by CarlosNZ** [comment]
I just remembered that we'd need to trigger it again when applicant's re-submit (application_status_history insert), as that would set the reviewer's action back to "Re-Review"
