### ISSUE TITLE
Remove unused sql functions

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/conforma-server#991]
[In this PR ](https://github.com/openmsupply/conforma-server/pull/989) application list was changed and previous functions were removed, then those functions were introduced because some were used elsewhere in code. Still some unused functions remain, they should be removed, but we need to check that they are unused (global search for both camel and snake case in both repos)

Is it possible that they are used in configurations ?

**Comment by CarlosNZ** [comment]
> Is it possible that they are used in configurations ?

I don't think so. There almost was once, but I'm pretty sure I found a better way to deal with it.
